Stickers
AlanMorel/MapleServer2 pull request #125
Opened 2021-01-13 07:09 UTC by Zintixx

2021-01-13 13:23 UTC, angelotadeucci approved these changes

2021-01-13 14:39 UTC, AlanMorel approved these changes

2021-01-14 00:17 UTC, rhydev requested changes
Can we name the handlers and packets after the opcode similar to all other packets and handlers?

2021-01-14 02:25 UTC, rhydev approved these changes

2021-01-14 02:25 UTC, merged