Feat: Stat points incrementation from trophies/prestige etc
AlanMorel/MapleServer2 pull request #141
Opened 2021-01-23 23:41 UTC by Andrew-Gan

### Variables
`public Dictionary<byte, int> OtherStats { get; private set; }`
- added dictionary which keeps track of attribute points gained via prestige/awards/etc
- keys (also used for sending packets)
  - `0x01` - PointsFromTrophy
  - `0x02` - PointsFromQuest
  - `0x03` - PointsFromExploratio
  - `0x04` - PointsFromPrestige

### StatDistribution.cs
`public void AddTotalStatPoints(int amount, byte pointSrc);`
- added new function; invoked when gaining attribute points via prestige/awards/etc
- increments TotalStatPoints by amount
- increments corresponding value in OtherStats

`public StatDistribution(Dictionary<byte, int> AllocatedStats, Dictionary<byte, int> OtherStats);`
- added constructor which initializes OtherStats

### StatPointPacket.cs
`public static Packet WriteTotalStatPoints(Player character);`
- fully implemented total attribute points packet (thanks @nobodylikesaleech )
- send opcode 0x0046 (STAT_POINT), total points mode 0x0, number of sources from which player has received point
- index of each source of attribute points same as above

### Temporary
- added calls to `AddTotalStatPoints(int, byte)` in `StatDistribution()` to demonstrate correctness

Related info can be found here: https://github.com/AlanMorel/MapleServer2/pull/103

2021-01-23 23:45 UTC, AlanMorel commented on MapleServer2/Types/StatDistribution.cs
> +        // key: 01 PointsFromTrophy, 02 PointsFromQuest, 03 PointsFromExploration, 04 PointsFromPrestige
Maybe if you turn this into an enum, you don't need this comment, then in lines 26-29, you can use the enum there directly, which also helps self-document the code

2021-01-23 23:46 UTC, AlanMorel commented on MapleServer2/Types/StatDistribution.cs
> +        public StatDistribution(Dictionary<byte, int> AllocatedStats, Dictionary<byte, int> OtherStats)
You can combine these two constructors by making `OtherStats` optional and having it initialize to a blank dictionary if none is passed in

2021-01-23 23:47 UTC, AlanMorel commented on MapleServer2/Types/StatDistribution.cs
> +
Unneeded extra blank line

2021-01-24 00:13 UTC, angelotadeucci approved these changes

2021-01-24 00:13 UTC, angelotadeucci commented on MapleServer2/Packets/StatPointPacket.cs
> +            foreach (byte pointSrc in character.StatPointDistribution.OtherStats.Keys.ToList())
`.ToList()` is unnecessary.

2021-01-24 00:31 UTC, AlanMorel requested changes

2021-01-24 00:31 UTC, AlanMorel commented on MapleServer2/Packets/StatPointPacket.cs
> +            foreach (MapleServer2.Enums.OtherStatsIndex pointSrc in character.StatPointDistribution.OtherStats.Keys.ToList())
Can you import it so you don't need the `MapleServer2.Enums.` part

2021-01-24 00:48 UTC, Andrew-Gan commented
all suggested changes before this message were resolved

2021-01-24 06:14 UTC, AlanMorel approved these changes

2021-01-24 10:30 UTC, angelotadeucci approved these changes

2021-01-25 21:27 UTC, merged