Fix: Optimized ItemParser
AlanMorel/MapleServer2 pull request #152
Opened 2021-01-27 22:05 UTC by angelotadeucci

It only takes 30 seconds now! Yoo-hoo!

2021-01-27 22:16 UTC, AlanMorel requested changes

2021-01-27 22:16 UTC, AlanMorel commented on GameDataParser/Parsers/ItemParser.cs
> +                    if (individualBoxItem.Attributes["minCount"].Value.Contains("."))
this can be moved above the box and id parsing

2021-01-27 22:16 UTC, AlanMorel commented on GameDataParser/Parsers/ItemParser.cs
> +                        itemDrops[box].Add(new ItemContent(id, minAmount, maxAmount, dropGroup, smartDropRate, contentRarity, enchant, id2));
Create the instance of ItemContent before the if statement, then use it here and on line 62

2021-01-27 22:17 UTC, Sparkymod approved these changes
amazing

2021-01-27 22:51 UTC, rhydev requested changes

2021-01-27 22:51 UTC, rhydev commented on GameDataParser/Parsers/ItemParser.cs
> +                    long box = long.Parse(individualBoxItem.Attributes["individualDropBoxID"].Value);
I don't think we need to parse to long here, can just keep as string

2021-01-28 05:08 UTC, rhydev approved these changes

2021-01-28 05:27 UTC, merged