Cleanup & Fix: Refactored ItemEquipHandler
AlanMorel/MapleServer2 pull request #156
Opened 2021-01-28 16:41 UTC by angelotadeucci

- Added IsDress to ItemMetadata and parsing to ItemParser
- Refactored ItemEquipHandler
- Added function +GetEquippedInventory(InventoryTab) to Player

2021-01-28 20:03 UTC, rhydev requested changes

2021-01-28 20:03 UTC, rhydev commented on MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
> +            if (item.ItemSlot == ItemSlot.PA && equippedInventory[ItemSlot.CL] != null && equippedInventory[ItemSlot.CL].IsDress)
Can we combine dresses+weapons like the above if block?

2021-01-28 20:03 UTC, rhydev commented on MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
> +        }
These two functions seem entirely unnecessary

2021-01-28 21:51 UTC, rhydev requested changes

2021-01-28 21:51 UTC, rhydev commented on MapleServer2/Types/Player.cs
> +                case InventoryTab.Fragment:
Think we can just default here since none of this will be used

2021-01-28 22:00 UTC, rhydev approved these changes

2021-01-29 14:38 UTC, AlanMorel approved these changes

2021-01-29 14:38 UTC, merged