Feat: Parsing all Npc
AlanMorel/MapleServer2 pull request #162
Opened 2021-02-02 16:24 UTC by Sparkymod

## Npc Parsing
- Add `NpcMetadata` for all entities.
- Add `NpcStats` for NpcMetadata. _The order of this stats are not the same as for `PlayerStats`_
- Remove `MapNpc` and using `NpcMetadata` on MapParsing.

## Npc restruct
- Update `Mob & Npc` class to inherit from `NpcMetadata`.
- Add `AddBoss` for Boss types of Mob. Packet structure is slighly different. _This is added in this PR because is just 1 file being modify._
- Update `FieldManager` to filter Npc from Mobs with `Friendly` property.

Addressing Mobs and Npcs for parsing.
#88 
#63

2021-02-02 16:32 UTC, AlanMorel requested changes

2021-02-02 16:32 UTC, AlanMorel commented on MapleServer2/Types/Mob.cs
> +        //public PlayerStats Stats;
Why comment out instead of remove?

2021-02-02 16:57 UTC, Sparkymod commented on MapleServer2/Types/Mob.cs
> +        //public PlayerStats Stats;
My bad, remove from npc and forgot mob

2021-02-03 21:04 UTC, angelotadeucci approved these changes

2021-02-08 22:10 UTC, AlanMorel approved these changes

2021-02-10 14:03 UTC, merged