Feat: Stat allocation/updates + Cleanup: PlayerStats
AlanMorel/MapleServer2 pull request #185
Opened 2021-02-21 22:48 UTC by quotopian

Includes a working implementation of player stats and stat point allocation; includes a basic rewrite of `PlayerStats`.

- Rewrite `PlayerStats` struct to a class.
   - Mimics order and behavior using the non-generic `OrderedDictionary`.
   - Includes stat Increase, Decrease methods, used to apply stat bonuses (e.g. gear).
   - Includes stat IncreaseBase, DecreaseBase methods, used to increase base stats.
   - Uses a `StatDistribution` to account for allocated points (at the moment).
   - Removes `CurrentHp` (use Hp, instead).
- Add server packet to update player's stats in a field in `StatPacket.cs`.
- Add logic to update player's stats on stat allocation in `StatPointHandler.cs`.

2021-02-21 23:01 UTC, angelotadeucci requested changes

2021-02-21 23:03 UTC, quotopian commented on MapleServer2/Packets/StatPacket.cs
> +            pWriter.WriteInt(player.ObjectId);  // ObjectId (?)
Thought I removed that last night

2021-02-21 23:40 UTC, angelotadeucci approved these changes

2021-02-22 01:06 UTC, Sparkymod requested changes

2021-02-22 01:06 UTC, Sparkymod commented on MapleServer2/Packets/StatPacket.cs
> +            pWriter.WriteByte(0x23);            // Unknown
Instead of hardcoding, use the enum you already have.
```suggestion
            pWriter.WriteEnum(StatsMode.SendStats);
```

2021-02-22 01:24 UTC, AlanMorel approved these changes

2021-02-22 01:57 UTC, Sparkymod approved these changes

2021-02-22 02:09 UTC, merged