Feat: Interact object
AlanMorel/MapleServer2 pull request #188
Opened 2021-02-23 00:32 UTC by angelotadeucci

- Handling interact objects, especially binoculars and extractors.
- Small fix for out of bounds tp.

2021-02-23 01:02 UTC, AlanMorel requested changes

2021-02-23 01:02 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
> +            foreach (MapInteractActor actor in MapEntityStorage.GetInteractActors(session.Player.MapId))
Could use linq here 😉

2021-02-23 01:03 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
> +            foreach (MapInteractActor actor in MapEntityStorage.GetInteractActors(session.Player.MapId))
oh yeah, idk why I didn't use

2021-02-23 03:46 UTC, AlanMorel approved these changes

2021-02-23 05:01 UTC, Sparkymod approved these changes

2021-02-26 00:10 UTC, AlanMorel approved these changes

2021-02-26 00:11 UTC, merged