Chat Sticker expiration parsing
AlanMorel/MapleServer2 pull request #191
Opened 2021-02-24 07:38 UTC by Zintixx

- Revised parsing for function parameters to consider more parameters than just id
- Included other function parameter data parsed. Note this is not all the function parameters have been parsed yet.
- Moved chat stickers to it's own class

2021-02-24 23:04 UTC, angelotadeucci approved these changes

2021-02-25 02:41 UTC, AlanMorel requested changes

2021-02-25 02:41 UTC, AlanMorel commented on GameDataParser/Parsers/ItemParser.cs
> +                if (contentType == "OpenMassive")
Could be `else if`

2021-02-26 00:17 UTC, angelotadeucci approved these changes

2021-02-26 02:03 UTC, merged