Cleanup: Fix all issues found by editorconfig
AlanMorel/MapleServer2 pull request #193
Opened 2021-02-26 21:21 UTC by angelotadeucci

- Dotnet-format
- Using Linq in `InsigniaHandler.cs`

2021-02-26 21:22 UTC, AlanMorel requested changes

2021-02-26 21:22 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/GroupChatHandler.cs
> +        private static void HandleCreate(GameSession session/*, PacketReader packet*/)
If we aren't using this at all, might as well remove

2021-02-26 22:38 UTC, AlanMorel approved these changes

2021-02-27 05:18 UTC, Sparkymod approved these changes

2021-02-27 06:44 UTC, merged