Feature: Item Exchange
AlanMorel/MapleServer2 pull request #196
Opened 2021-03-01 04:32 UTC by Zintixx

- This is for exchanging fragments( or scrolls) for items.
- Parsing data required for item exchange (fusion) including meso cost, item(s) cost, and exchange item(s)
- Uses the same checks on recipe from MasteryHandler.
- Small fix on MasteryHandler to subtract the correct amount.

Also, not sure what the standard was when it comes to item parsing whether it should be included all in ItemParser.cs or have it's own Parser like how I currently have it.

2021-03-01 04:41 UTC, AlanMorel requested changes

2021-03-01 04:41 UTC, AlanMorel commented on GameDataParser/Parsers/ItemExchangeScrollParser.cs
> +                        if (childNode.Name == "receipe")
typo?

2021-03-01 04:41 UTC, AlanMorel commented on GameDataParser/Parsers/ItemExchangeScrollParser.cs
> +                                if (itemNode.Name == "item")
Invert and continue

2021-03-01 04:41 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/ItemExchangeHandler.cs
> +                if (RemoveRequiredItemsFromInventory(session, exchange, item, quantity))
Invert and return

2021-03-01 04:41 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/ItemExchangeHandler.cs
> +                    Item exchangeRewardItem = new(exchange.RewardId)
84-91 matches 96-104 almost exactly, maybe do
```InventoryController.Consume(session, item.Uid, exchange.RecipeAmount * quantity);``` in that else, then the rest can be the code where they are identical

2021-03-01 04:41 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/ItemExchangeHandler.cs
> +                if (item != null)
Invert and continue

2021-03-01 04:43 UTC, Zintixx commented on GameDataParser/Parsers/ItemExchangeScrollParser.cs
> +                        if (childNode.Name == "receipe")
yes but not from me

2021-03-01 05:44 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/ItemExchangeHandler.cs
> +                    }
Can't use `Consume()` here too?

2021-03-01 06:08 UTC, Zintixx commented on MapleServer2/PacketHandlers/Game/ItemExchangeHandler.cs
> +                    }
oh yeah oops

2021-03-01 12:38 UTC, Sparkymod approved these changes
Nice!

2021-03-02 19:02 UTC, angelotadeucci approved these changes

2021-03-02 23:12 UTC, merged