PremiumClub Parsing
AlanMorel/MapleServer2 pull request #205
Opened 2021-03-03 01:13 UTC by Zintixx

- Parsing Premium Club packages and daily items.
- Removed Player.isVIP to check on expiration of a player's vip/premium club status on Insignia

2021-03-03 01:31 UTC, AlanMorel requested changes

2021-03-03 01:31 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
> +            long expiration = DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (vipPackage.VipPeriod * 3600); // Convert to seconds, as vipPeriod is given as hours
You can make `vipPackage.VipPeriod * 3600` a variable then use here and on line 121

2021-03-03 01:31 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
> +            if (session.Player.VIPExpiration < DateTimeOffset.UtcNow.ToUnixTimeSeconds())
Looks this could be replaced with:
`if (!IsVip(session.Player)) {`

2021-03-03 01:53 UTC, AlanMorel approved these changes

2021-03-04 15:06 UTC, Sparkymod approved these changes

2021-03-04 19:40 UTC, angelotadeucci requested changes

2021-03-04 19:40 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
>          }
Shouldn't this function be in Player instead?

2021-03-04 19:40 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/PremiumClubHandler.cs
> +            if (!session.Player.Wallet.Meret.Modify(vipPackage.Price))
If it's possible to buy VIP with any type of Meret you need to use `Wallet.RemoveMerets()`

2021-03-04 20:32 UTC, angelotadeucci requested changes

2021-03-04 20:32 UTC, angelotadeucci commented on MapleServer2/Types/Player.cs
> +        }
I would prefer something like this.
```suggestion
        public bool IsVip()
        {
            return VIPExpiration > DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        }
```
And then you change in PremiumClubHandler.cs to `if (!session.Player.IsVip())`

2021-03-04 20:41 UTC, angelotadeucci approved these changes
👌

2021-03-06 01:41 UTC, merged