Spawn block offset and rotation fix
AlanMorel/MapleServer2 pull request #212
Opened 2021-03-12 17:34 UTC by Zintixx

Fix for moving fields. It should now behave like it does in the game:

- Rotation added to face the correct way
- If the portal was a cube , you spawn one block away from the cube rather than on it. The spawn block depends on the rotation.
- I've also removed a null skip on "TargetFieldSN" in MapEntityParser. This is important for same-map teleporting.

2021-03-12 17:41 UTC, AlanMorel requested changes

2021-03-12 17:41 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
> +                    int offset = 150;
I think 150 is already a constant somewhere

2021-03-12 23:49 UTC, AlanMorel approved these changes

2021-03-13 05:02 UTC, angelotadeucci approved these changes

2021-03-15 00:50 UTC, merged