Feat: Add mob region spawns
AlanMorel/MapleServer2 pull request #214
Opened 2021-03-15 06:15 UTC by quotopian

Adds all parsing, serialization, and deserialization functionality for field mob spawns.

Todo: Extend spawns to include chests, bosses, event mobs. Clean up mob spawning. Find NPC lists for spawns.

2021-03-15 13:41 UTC, AlanMorel requested changes

2021-03-15 13:41 UTC, AlanMorel commented on MapleServer2/Tools/SpawnGenerator.cs
> +            int blockSize = 150;
This is already a constant in the source

2021-03-15 23:56 UTC, AlanMorel approved these changes

2021-03-17 15:20 UTC, angelotadeucci approved these changes

2021-03-17 16:00 UTC, merged