Feat: ophelia and scrolls stat roll
AlanMorel/MapleServer2 pull request #216
Opened 2021-03-17 22:52 UTC by angelotadeucci

- Reworked ItemStats (again):
     - One list of `ItemStat` for each `BasicAttributes` and `BonusAttributes`;
     - Functions to get new roll new attributes and values. `RollBasicStats`, `RollBonusStats` and `RollNewBonusValues`.

- Handling changing attributes trough Ophelia and scrolls.
- Removed `StateStorage` from `Session.cs` and added to `Inventory.cs`
- Changed `HpOnKill` attribute to flat instead of percent.

2021-03-17 22:56 UTC, AlanMorel approved these changes

2021-03-20 08:15 UTC, Sparkymod approved these changes

2021-03-20 16:28 UTC, AlanMorel requested changes

2021-03-20 16:28 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/ChangeAttributesHandler.cs
> +            }
Lines 127-134 can be 1-2 lines max by using math min

2021-03-20 16:28 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/ChangeAttributesHandler.cs
> +                {0, 200}, {1, 250}, {2, 312}, {3, 390}, {4, 488},
Would this be more readable 1 per line?

2021-03-20 19:29 UTC, AlanMorel approved these changes

2021-03-22 23:56 UTC, AlanMorel approved these changes

2021-03-26 19:30 UTC, merged