Feat: Buddy List and Music Compose
AlanMorel/MapleServer2 pull request #218
Opened 2021-03-20 08:24 UTC by Zintixx

## Buddy List
Implemented Buddy List. This also includes partial Block functionality. 
Buddy system works by a shared ID system. Both players are connected by the ID in order to get each other's information on each Buddy List.
There's a few things in the current implementation that are temporary (as indicated as comments) until a database is set up.

## Music Compose
Adjusted the WriteItem packet to work with UGC Scores.
Parsing "isCustomNote" to find the items that are UGCScores.
Music composing should now work as intended. 
Listening to music for _other_ players in the map still does not work. I left a comment as to what needs to be fixed.

### Etc
Moved all of the function Item data to it's own class. This should make it a bit cleaner.

2021-03-20 08:39 UTC, Sparkymod requested changes

2021-03-20 08:39 UTC, Sparkymod commented on Maple2Storage/Types/Metadata/ItemMetadata.cs
> +    public class Function
`Function` probably would be confuse with something else, perhaps `ItemFunction` or `ItemMetadataFunction`

2021-03-20 08:39 UTC, Sparkymod commented on MapleServer2/PacketHandlers/Game/BuddyHandler.cs
> +        public enum BuddyNotice : byte
Can move this enum right below the other enum on line 28

2021-03-20 08:39 UTC, Sparkymod commented on MapleServer2/PacketHandlers/Game/BuddyHandler.cs
> +        private static void HandleDecline(GameSession session, PacketReader packet)
Empty space between methods

2021-03-20 08:39 UTC, Sparkymod commented on MapleServer2/PacketHandlers/Game/InstrumentHandler.cs
>          private static void HandleFireworks(GameSession session)
Empty line between methods

2021-03-20 08:39 UTC, Sparkymod commented on MapleServer2/Packets/BuddyPacket.cs
> +
Extra line here

2021-03-20 16:34 UTC, AlanMorel requested changes

2021-03-20 16:34 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/BuddyHandler.cs
> +            if ((byte) session.Player.BuddyList.Count(b => b.Blocked != true) >= 100) // 100 is friend limit
can this just be `!b.Blocked`?

2021-03-21 05:52 UTC, Sparkymod approved these changes

2021-03-21 15:16 UTC, angelotadeucci requested changes

2021-03-21 15:16 UTC, angelotadeucci commented on MapleServer2/Packets/InstrumentPacket.cs
> +            }
```suggestion
           if (score.IsCustomScore)
            {
                pWriter.WriteMapleString(score.Score.Notes);
            }
            else
            {
                pWriter.WriteUnicodeString(score.FileName);
            }
```

2021-03-21 15:16 UTC, angelotadeucci commented on MapleServer2/Packets/BuddyPacket.cs
> +            pWriter.WriteInt((int) buddy.Friend.JobCode);
```suggestion
            pWriter.WriteEnum(buddy.Friend.Job);
            pWriter.WriteEnum(buddy.Friend.JobCode);
```

2021-03-21 15:16 UTC, angelotadeucci commented on MapleServer2/Packets/BuddyPacket.cs
> +            pWriter.WriteInt(buddy.Friend.Trophy[2]);
Up to you.

```suggestion
           foreach (int trophyCount in buddy.Friend.Trophy)
            {
                pWriter.WriteInt(trophyCount);
            }
```

2021-03-21 18:17 UTC, angelotadeucci approved these changes

2021-03-26 23:02 UTC, AlanMorel approved these changes

2021-03-27 15:54 UTC, angelotadeucci approved these changes

2021-03-27 18:07 UTC, merged