Feat: Add skill book reset. Fix skill book open/save. Fix mob stats.
AlanMorel/MapleServer2 pull request #220
Opened 2021-03-22 09:09 UTC by quotopian

## Additions
- Skill book can now reset allocations.
- Skills can now consume SP and EP (stamina).

## Fixes
- Mob stats are now parsed correctly.
- Skill book now saves skill points correctly.
- Skill book now opens correctly with a functioning UI.
---------------------------------------------------------------------
TODO: Add multiple skill tabs.

2021-03-22 16:19 UTC, angelotadeucci requested changes

2021-03-22 16:19 UTC, angelotadeucci commented on GameDataParser/Parsers/SkillParser.cs
> +                    bool skillRecovery = (int.Parse(document.SelectSingleNode("/ms2/basic/kinds").Attributes["spRecoverySkill"]?.Value ?? "0") > 0) ? true : false;
```suggestion
                    bool skillRecovery = int.Parse(document.SelectSingleNode("/ms2/basic/kinds").Attributes["spRecoverySkill"]?.Value ?? "0") > 0;
```

2021-03-22 16:19 UTC, angelotadeucci commented on Maple2Storage/Types/NpcStats.cs
>          public NpcStat(T total, T min, T max)
Should rename the parameters too so it's less confusing

2021-03-22 16:19 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/JobHandler.cs
> +                case 0x0A:
Should use an enum for the cases

2021-03-22 16:19 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/SkillBookTreeHandler.cs
> +                case 0x04:
Use enum here too

2021-03-22 16:19 UTC, angelotadeucci commented on MapleServer2/Packets/JobPacket.cs
> +                pWriter.WriteByte((skills[id] > 0) ? 1 : 0);    // Is it learned?
```suggestion
                pWriter.WriteBool(skills[id] > 0);    // Is it learned?
```

2021-03-22 23:18 UTC, AlanMorel requested changes

2021-03-22 23:18 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/JobHandler.cs
> +                    break;
Add default logger like other handlers

2021-03-22 23:18 UTC, AlanMorel commented on MapleServer2/Packets/JobPacket.cs
> +        //public static Packet WriteSkills(this PacketWriter pWriter, Player character)
Why?

2021-03-22 23:40 UTC, quotopian commented on MapleServer2/Packets/JobPacket.cs
> +        //public static Packet WriteSkills(this PacketWriter pWriter, Player character)
I was planning to remove out of draft.

2021-03-23 04:09 UTC, angelotadeucci approved these changes

2021-03-23 21:13 UTC, AlanMorel approved these changes

2021-03-26 19:31 UTC, merged