Feat: Meret Market & Gacha Capsules
AlanMorel/MapleServer2 pull request #224
Opened 2021-03-27 18:51 UTC by Zintixx

## Meret Market
Implemented Meret Market - only the home page and premium section (no UGC/Design shop).
The home page heavily relies on banner images from a web server however there were some default in-game 'banners' that are able to be used.
Multi item buying (through the cart) is added.

## Gachapon/Capsules
Capsules have been implemented. Ducky Outfit Capsules tend to have 'SmartGender' which means anything a player gets will be their gender. In order to achieve this, I have a do while loop to keep looping until it randomly picks a gender of the character.
Capsule shops have _not_ been implemented. This requires knowing the exact Shop category string in order to correctly have it display in the shop.  I'm not sure how we could achieve this.
Outfits/Items obtained from capsules cannot be broken down to coins has not been implemented.

### Various other fixes
Added a shop type enum. This will tell the client what shop "skin" to use.
Added PercussionId to the `InstrumentPacket PlayScore` packet. This allows for percussion instruments to properly play their sound.
Adjusted Super World Chat to use the item's ID rather than the function ID. This fix was needed for item copies of the same item but different IDs.

2021-03-27 19:05 UTC, AlanMorel requested changes

2021-03-27 19:05 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/MeretMarketHandler.cs
> +                item.ExpiryTime = DateTimeOffset.UtcNow.ToUnixTimeSeconds() + Environment.TickCount + (marketItem.Duration * 86400);
Can the 86400 be broken down into further smaller multiplication so its more obvious what it represents?

2021-03-27 19:05 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/RequestItemUseHandler.cs
> +            if (contents.SmartGender)
You can invert and immediately return contents

2021-03-28 00:24 UTC, AlanMorel approved these changes

2021-04-01 15:12 UTC, Sparkymod approved these changes

2021-04-01 15:25 UTC, angelotadeucci approved these changes

2021-04-01 18:18 UTC, merged