Feat: WIP NpcTalking / QuestHandling
AlanMorel/MapleServer2 pull request #225
Opened 2021-03-31 22:48 UTC by angelotadeucci

- Rewrite of `ScriptParser` / `ScriptMetadata`;
- WIP for `NpcTalkHandler.cs`.

### QuestHandler
- Add next quest when completing a quest;

2021-03-31 22:54 UTC, AlanMorel approved these changes

2021-03-31 23:04 UTC, Zintixx commented
We probably should be filtering out KR/CN/JP locales in scripts too

2021-04-02 04:06 UTC, AlanMorel requested changes

2021-04-02 04:06 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
> +                && scriptMetadata.Options.First(x => x.Id == npcTalk.ScriptId).AmountContent <= npcTalk.ContentIndex
can you cache `scriptMetadata.Options.First(x => x.Id == npcTalk.ScriptId)` so you don't need to query it twice?

2021-04-02 04:06 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
> +                        return scriptMetadata.Options.First(x => x.Id == npcTalk.ScriptId).Goto[index];
I think you can cache `scriptMetadata.Options.First(x => x.Id > npcTalk.ScriptId)` here too

2021-04-02 15:28 UTC, angelotadeucci commented
#88

2021-04-05 01:01 UTC, AlanMorel approved these changes

2021-04-05 12:29 UTC, Sparkymod approved these changes

2021-04-05 13:45 UTC, AlanMorel requested changes

2021-04-05 13:45 UTC, AlanMorel commented on MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
> +            if (scriptMetadata.Options.First(x => x.Id == npcTalk.ScriptId).AmountContent > 1)
```scriptMetadata.Options.First(x => x.Id == npcTalk.ScriptId)``` should probably be set to a variable so it doesn't need to be queried twice

2021-04-05 15:47 UTC, AlanMorel approved these changes

2021-04-05 15:47 UTC, merged