Party fixes
AlanMorel/MapleServer2 pull request #228
Opened 2021-04-02 02:57 UTC by Zintixx

The biggest changes to parties are the following four points:
1. Writing HP of the player in the WriteCharacter packet. This solves needing to send unnecessary packets to the player upon first joining a party.
2. Implement the ability to request to join a party if a party exists.
3. Above all else, when you invite players to a new party or by making a recruitment listing, the server makes a party in order for the other player(s) to join. We're treating a party of 1 as if the player is _not_ in a party. This allows players to invite others to a party if they've already established a 1 player party (i.e. if player a invites player b to a new party, but player c invites player a).
4. Implemented `PartyNotice` for the various different errors parties come across.

Party kicking and party matching (for dungeons) is not yet implemented.
Initial dungeon handler and packets added. Still very much a WIP. Main focus of these were party handling.

#85

2021-04-02 15:26 UTC, angelotadeucci requested changes

2021-04-02 15:26 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/DungeonHandler.cs
> +            }
```suggestion
                MapleServer.BroadcastPacketAll(DungeonHelperPacket.BroadcastAssist(newParty, dungeonId));
                return;
            }
            
            Party party = GameServer.PartyManager.GetPartyById(session.Player.PartyId);
            party.BroadcastPacketParty(PartyPacket.PartyHelp(dungeonId));
            MapleServer.BroadcastPacketAll(DungeonHelperPacket.BroadcastAssist(party, dungeonId));
```

2021-04-02 15:26 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/PartyHandler.cs
> +                    }
Preferably remove the else and add an return inside the if

2021-04-02 15:26 UTC, angelotadeucci commented on MapleServer2/Packets/PartyPacket.cs
> +
extra blank line

2021-04-02 15:26 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/DungeonHandler.cs
> +
extra blank line

2021-04-05 01:01 UTC, AlanMorel approved these changes

2021-04-05 01:06 UTC, angelotadeucci approved these changes

2021-04-05 12:25 UTC, Sparkymod approved these changes

2021-04-05 13:44 UTC, merged