Feat: Pet Skin and Glamour Anvil and Color changes
AlanMorel/MapleServer2 pull request #231
Opened 2021-04-05 16:30 UTC by Zintixx

3 main updates to this: Item Extraction, Pet Skin Scrolls, and Color changes
## Item Extraction
Implemented Item Extraction aka Glamour Anvils
Parsing `itemextraction.xml` for needed data.
Adjusted `Item` to grab the correct amount of glamour forges remaining

## Pet Skin Scrolls
Implemented Pet Skin scrolls (ability to make a pet skin badge).

## Color Changes
Now correctly writing color for items.
`ItemMetadataStorage.GetEquipColor` shows how a color is determined for an item.
Revised `EquipColor` to contain `MixedColor`, Color Index, and Color Palette.
Added `MixedColor`. This struct _ONLY_ has color to it.
Removed AppearanceFlag in `Item`. This turned out to be Color Palette.

### Other
Added all the Gacha shops
Implemented HatData. This contains the position information for hats.
Revised `ShopHandler` to send each shop item as it's own packet. This is normally how it is behaved in game. With the changes needed on Gacha shops, it required sending each packet individually.
Now adding in items received from gacha capsules the dismantle information. Also reflected in `WriteItem`

2021-04-05 16:39 UTC, AlanMorel requested changes

2021-04-05 16:39 UTC, AlanMorel commented on GameDataParser/Parsers/ColorPaletteParser.cs
>                      Color.Argb(primaryBytes[0], primaryBytes[1], primaryBytes[2], primaryBytes[3]),
Optional but could be cool to have a method called FromBytes in Color that just takes in bytes and does this whole index thing there

2021-04-07 00:29 UTC, AlanMorel approved these changes

2021-04-07 16:55 UTC, angelotadeucci commented on MapleServer2/Constants/RecvOp.cs
> +        REQUEST_SET_BUILD_MODE = 0x0036,
Rename `SET_CRAFT_MODE` on **SendOp** too

2021-04-07 16:55 UTC, angelotadeucci commented on MapleServer2/PacketHandlers/Game/RequestGemEquipmentHandler.cs
> +
blank line

2021-04-07 16:55 UTC, angelotadeucci commented on MapleServer2/Packets/ItemExtractionPacket.cs
> +
blank line

2021-04-07 16:55 UTC, angelotadeucci commented on MapleServer2/Packets/PetSkinPacket.cs
> +
blank line

2021-04-07 22:11 UTC, angelotadeucci approved these changes

2021-04-10 01:26 UTC, merged