Add mob drops (no items), basic damage calculation, out-of-combat timer.
AlanMorel/MapleServer2 pull request #266
Opened 2021-06-07 03:35 UTC by quotopian

Basically, a lot of clean-up and logic fixes regarding combat. Adds extra parsing on skill metadata and mob (NPC) metadata.

## Fixes:
- Crits are consistent with skillcasts.
- Player stats' thread-safety.

## Additions:
- Players recover to out-of-combat state after 5 seconds.
- Parse mob exp (uses exp table 1).
- Mob exp gain.
- Meso drops (50% chance, random amount).
- SP orb drops (~16% chance).
- Stamina/EP orb drops (10% chance).
- Handling meso/meret/EXP/SP/Stamina resource pickups.
- Basic damage calculation based off [this formula](https://static.wikia.nocookie.net/maplestory2_gamepedia/images/a/ab/DamageFormula.png/revision/latest?cb=20181103224755).

2021-06-07 12:39 UTC, AngeloTadeucci approved these changes

2021-06-07 12:39 UTC, AngeloTadeucci commented on MapleServer2/PacketHandlers/Game/JobHandler.cs
> +using MaplePacketLib2.Tools;
New `usings` but not being used?

2021-06-07 14:46 UTC, AlanMorel requested changes

2021-06-07 14:46 UTC, AlanMorel commented on MapleServer2/Types/Player.cs
> +                        if (Stats[statId].Current < Stats[statId].Max)
Perhaps invert this and return, then the rest under it?

2021-06-11 07:25 UTC, AlanMorel approved these changes

2021-06-11 13:43 UTC, AngeloTadeucci approved these changes

2021-06-14 14:42 UTC, merged