Quick fix: Remove status duration
AlanMorel/MapleServer2 pull request #293
Opened 2021-07-05 02:01 UTC by Sparkymod

2021-07-05 12:51 UTC, darkvergus approved these changes

2021-07-05 20:07 UTC, AngeloTadeucci approved these changes

2021-07-05 22:49 UTC, AlanMorel requested changes

2021-07-05 22:49 UTC, AlanMorel commented on MapleServer2/Types/Status.cs
> +            Stacks = stacks >= 1 ? stacks : 1;
could use math max here

2021-07-05 23:05 UTC, Zintixx approved these changes

2021-07-06 04:09 UTC, AlanMorel approved these changes

2021-07-06 04:10 UTC, merged