Feat: Additional Data to Skills. Parsing DurationTick ✔
AlanMorel/MapleServer2 pull request #297
Opened 2021-07-11 17:46 UTC by Sparkymod

## Skills ✨
- Parsing SubType and DurationTick on skills.
- Adding type `SkillAdditionalData` since this will have many more data to be add for status types, buff types, power ups on skills, splash effects, etc..

Open to suggestions 😊

2021-07-11 18:02 UTC, AngeloTadeucci approved these changes

2021-07-11 23:00 UTC, darkvergus approved these changes

2021-07-12 02:37 UTC, AlanMorel requested changes

2021-07-12 02:37 UTC, AlanMorel commented on GameDataParser/Parsers/SkillParser.cs
> +                if (entry.Name.StartsWith("additionaleffect"))
You can invert and continue

2021-07-12 23:51 UTC, merged