Feat: Lua scripting
AlanMorel/MapleServer2 pull request #332
Opened 2021-08-13 18:13 UTC by AngeloTadeucci

- Implemented loading lua scripts;
- Implemented World Map graph for pathfinding;
- Added taxi and air taxi cost formulas. Thanks @sharrman and @kOchirasu #296

2021-08-13 22:38 UTC, Sparkymod approved these changes

2021-08-13 22:53 UTC, AlanMorel requested changes

2021-08-13 22:53 UTC, AlanMorel commented on MapleServer2/Scripts/calcAirTaxiCharge.lua
> +    return 30000 + math.max(playerLevel - 10, 0) * 500
Can 30000 be put into a variable, like `baseFare` or something?

2021-08-13 22:53 UTC, AlanMorel commented on MapleServer2/Tools/LuaLoader.cs
> +    public class LuaLoader
Can you abstract this to just `ScriptLoader` rather than hardcoding the script language?

2021-08-13 22:53 UTC, AlanMorel commented on MapleServer2/Tools/LuaLoader.cs
> +                Script.DoFile($"Scripts/{scriptName}.lua");
can `.lua` be put into a variable called `scriptExtension` or something?

2021-08-13 23:39 UTC, AlanMorel approved these changes

2021-08-17 14:19 UTC, Sparkymod approved these changes

2021-08-17 14:29 UTC, merged