Parsing vibrate objects + trigger chain breaking fixed
AlanMorel/MapleServer2 pull request #424
Opened 2021-09-27 16:30 UTC by Clockworkx

### parsing vibrate objects
vibrate objects added to the field. 

### trigger chain
fixed a bug which caused the trigger chain to break when non-existing trigger objects were requested by the client

2021-09-27 16:38 UTC, Zintixx requested changes

2021-09-27 16:38 UTC, Zintixx commented on MapleServer2/Managers/FieldManager.cs
> +                //trigger.Next();
What's this change for?

2021-09-27 16:38 UTC, Zintixx commented on MapleServer2/Triggers/FieldObjectTriggers.cs
> +        public void SetSkill(int[] triggerIds, bool arg)
could be good to keep the it named `arg2` until we figure out what it really is. Just so we can refer to the scripts referring to an arg2.

2021-09-27 17:10 UTC, AngeloTadeucci requested changes

2021-09-27 17:10 UTC, AngeloTadeucci commented on Maple2Storage/Types/Metadata/MapEntityMetadata.cs
> +
```suggestion
```

2021-09-27 17:10 UTC, AngeloTadeucci commented on MapleServer2/Triggers/FieldObjectTriggers.cs
> +                if (Field.State.TriggerEffects.ContainsKey(triggerId))
Instead of `ContainsKey` change it to `TryGetValue`

2021-09-27 17:10 UTC, AngeloTadeucci commented on MapleServer2/Triggers/FieldObjectTriggers.cs
> +                if (Field.State.TriggerMeshes.ContainsKey(triggerMeshId))
Instead of `ContainsKey` change it to `TryGetValue`

2021-09-28 13:34 UTC, AngeloTadeucci approved these changes

2021-09-28 13:40 UTC, darkvergus approved these changes

2021-09-28 14:17 UTC, merged