Fix: more dynamic trophy update
AlanMorel/MapleServer2 pull request #496
Opened 2021-12-16 08:46 UTC by AngeloTadeucci

- Dynamic trophy update:
    - Find all trophies that use the condition type, code and target;
    - Update all trophies which match the conditions.
- Added a Level Up Command.

##
Worried about performance of the function **TrophyUpdate** because of searching trough all trophy metadatas to find the correct condition, I did some tests with this snippet:

```cs
Stopwatch sw = Stopwatch.StartNew();
for (int i = 0; i < 100; i++)
{
    trigger.Session.Player.TrophyUpdate("jump", 1);
}
sw.Stop();
```

The result was ~220ms for all 100 iterations with saving to database.

Without saving to database the time was ~8ms for 100 iterations.

2021-12-16 10:14 UTC, darkvergus approved these changes

2021-12-16 15:27 UTC, AlanMorel requested changes

2021-12-16 15:27 UTC, AlanMorel commented on MapleServer2/Commands/Game/PlayerCommands.cs
> +            ;
Weird formatting?

2021-12-17 02:02 UTC, AlanMorel approved these changes

2021-12-17 02:07 UTC, Zintixx approved these changes

2021-12-17 03:43 UTC, merged