Feat: UGC Banners
AlanMorel/MapleServer2 pull request #603
Opened 2022-04-15 06:45 UTC by AngeloTadeucci

2022-04-15 19:52 UTC, AlanMorel requested changes

2022-04-15 19:52 UTC, AlanMorel commented on MapleServer2/Packets/UGCPacket.cs
> +        const int LoopCounter = 1; // not sure when more than 1 is used
`loopCounter`

2022-04-15 21:22 UTC, AngeloTadeucci commented
Updated @Zintixx @AlanMorel

2022-04-15 21:26 UTC, Zintixx approved these changes

2022-04-16 01:19 UTC, AlanMorel approved these changes

2022-04-16 04:27 UTC, Sparkymod approved these changes

2022-04-16 23:14 UTC, merged