NPC Talk Rework and Enchanting additions/fixes
AlanMorel/MapleServer2 pull request #647
Opened 2022-05-28 19:06 UTC by Zintixx

- scripts/quests are now parsed using `Maple2.File.Parser`
- Rework on NPC talk. 
 - Any additional recommendations is appreciated
- Implemented enchanting dialog for Peachy and Ophelia
- Implements NPC Job scripts. Note not all are implemented right now. Will come in later PR.
- Implements enchanting server notices if enchant level is 12 or above
- Added additional NPC lua scripts
- Fixed shops. Turns out there is no "uid". it's just shop id. Shop Items reflect this change
- Fixes #636 
- Fixes #635 
- Fixes #646

2022-05-28 19:49 UTC, AngeloTadeucci requested changes

2022-05-28 19:49 UTC, AngeloTadeucci commented on Maple2Storage/Scripts/Npcs/11000254.lua
> +    print(itemCount)
```suggestion
```

2022-05-28 19:49 UTC, AngeloTadeucci commented on Maple2Storage/Scripts/Npcs/11000508.lua
> +    elseif enchantLevel <= 2 then
`return 1998 + enchantLevel`?

2022-05-28 19:49 UTC, AngeloTadeucci commented on Maple2Storage/Scripts/Npcs/11000510.lua
> +    elseif enchantLevel <= 2 then
same thing here `return 1998 + enchantLevel`?

2022-05-28 19:49 UTC, AngeloTadeucci commented on Maple2Storage/Scripts/Npcs/11000994.lua
> +    end
```suggestion
    return ScriptManager.GetPlayer().HasQuestStarted(10001840)
```

2022-05-28 19:49 UTC, AngeloTadeucci commented on MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
> +    private static NpcScript GoToScript(GameSession session, int selectedIndex, NpcScript currentScript, NpcTalk npcTalk, ScriptMetadata metadata)
new line before

2022-05-28 19:49 UTC, AngeloTadeucci commented on MapleServer2/Types/BankInventory.cs
>          session.Send(StorageInventoryPacket.Expand(ExtraSize));
Expand twice? 🤔

2022-05-28 19:52 UTC, darkvergus commented on MapleServer2/Database/Seeding/ShopItemsSeeding.sql
> +    `shop_id`                         int         DEFAULT NULL,
FIX TABBING MADGE

2022-05-28 19:52 UTC, darkvergus commented on MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
extra space

2022-05-28 19:52 UTC, darkvergus commented on MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
> +    private static NpcScript GoToScript(GameSession session, int selectedIndex, NpcScript currentScript, NpcTalk npcTalk, ScriptMetadata metadata)
space before the function

2022-05-28 22:43 UTC, Zintixx commented on MapleServer2/Types/BankInventory.cs
>          session.Send(StorageInventoryPacket.Expand(ExtraSize));
its sent twice. not sure why

2022-05-28 22:52 UTC, darkvergus approved these changes

2022-05-29 03:26 UTC, AngeloTadeucci approved these changes

2022-05-29 03:53 UTC, merged