Mob AI Infra v0.1
AlanMorel/MapleServer2 pull request #782
Opened 2022-10-17 23:28 UTC by AngeloTadeucci

This is the base of the new Mob AI. It works similar to triggers where each AIState has an OnEnter, Execute and OnExit

Example on how to implement new AI:
- MapleServer2/AIScripts/29000282/BelmaBehavior.cs 

Behavior applied to all mobs:
- MapleServer2/AIScripts/Default/DefaultState.cs
- MapleServer2/AIScripts/Default/DefaultPatrolState.cs
- MapleServer2/AIScripts/Default/DefaultPatrolState.cs

2022-10-19 02:50 UTC, Zintixx requested changes

2022-10-19 02:50 UTC, Zintixx commented on MapleServer2/AIScripts/PrisonGovernor2Battle.cs
> +    {
In the same sense that a field has Triggers and TriggerLoader, I feel as though we should do the same for NPCs, so we wouldn't have to feed in the NPC instance to get NPC variables and values.

2022-10-19 02:50 UTC, Zintixx commented on MapleServer2/AIScripts/PrisonGovernor2Battle.cs
> +        }
Likewise with this. `CheckHPThreshold` would be an AI function and not necessarily under NPC, like how we have `TriggerCondition` all in one area specifically for trigger scripts

2022-10-19 02:50 UTC, Zintixx commented on MapleServer2/AIScripts/PrisonGovernor2Battle.cs
> +            );
This is better but I think these could also be AI functions like `CheckHPThreshold`

2022-10-19 02:50 UTC, Zintixx commented on MapleServer2/AIScripts/PrisonGovernor2Battle.cs
> +        npc.Target.Value.Triggers.Add(new("battleStop", 1));
This should all be in an AI function, named something like `SetUserValue`

Essentially what I'm getting at with all these is that logic of each AI script shouldn't be in the AI script. This should all be in one/multiple AI files (like how we have Trigger functions).

Having logic per script would increase the tediousness of creating each script. It's like equivalent as if trigger scripts for maps had logic in them. They don't. Instead, they just have conditions, actions, and their respective parameters.

2022-10-19 02:53 UTC, Zintixx commented on MapleServer2/AIScripts/AiHelper.cs
> +    };
hmm is there a way to automate this? Could we just parse the ai script name from the NPC xmls without file extension and name the AI script exactly as it is?
Just thinking ahead when there's dozens and dozens more.

2022-10-19 03:43 UTC, Sparkymod requested changes

2022-10-19 03:43 UTC, Sparkymod commented on Maple2Storage/Types/Metadata/NpcMetadata.cs
> +    public Dictionary<NpcState, (string id, NpcAction action, short chance)[]> StateActions = new();
you can consider use a class or record at this stage rather than this generic, like NpcStateAction and have those 3 fields there.

2022-10-19 14:38 UTC, AlanMorel requested changes

2022-10-19 14:38 UTC, AlanMorel commented on MapleServer2/AIScripts/DefaultNew.cs
> +
Extra blank line

2022-10-19 21:45 UTC, AlanMorel approved these changes

2022-10-19 22:58 UTC, Zintixx requested changes

2022-10-19 22:58 UTC, Zintixx commented on MapleServer2/AI/Functions/AICondition.cs
> +    }
Couldn't this just be 1 function?

2022-10-19 23:00 UTC, AngeloTadeucci commented on MapleServer2/AI/Functions/AICondition.cs
> +    }
Oops, fixed. auto pilot

2022-10-19 23:13 UTC, Zintixx approved these changes

2022-10-20 03:49 UTC, Sparkymod approved these changes

2022-10-20 04:17 UTC, merged